;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        beginning-of-defun
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        dired-next-line
        dired-toggle-read-only
        dired-undo
        dired-unmark-backward
        electric-pair-delete-pair
        end-of-buffer
        eval-last-sexp
        find-file
        ibuffer
        sgml-slash
        string-rectangle
        suspend-frame
        wdired-exit
        wdired-finish-edit
        wdired-next-line
        xref-pop-marker-stack
        xterm-paste
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        indent-for-tab-command
        kill-region
        lldb-debug
        ))
